import type { Item } from "./types";

export const sampleItems: Item[] = [
  {
    id: "1",
    title: "iPhone 17 Pro Max",
    desc: "Blue color, no case.",
    location: "Senior High Gate",
    date: "2026-01-28",
    time: "12:30 PM",
    image: "/iPhone17.png",
    tags: ["FOUND", "REPORTED"],
  },
  {
    id: "2",
    title: "Key",
    desc: "3 small keys and 2 big Keys with anime key chain.",
    location: "Junior High Gymnasium",
    date: "2026-01-27",
    time: "06:00 PM",
    image: "/key.png",
    tags: ["FOUND", "REPORTED"],
  },
  {
    id: "3",
    title: "Classroom Key",
    desc: "5 Keys with pokemon key chain.",
    location: "Room 204",
    date: "2026-01-26",
    time: "12:00 PM",
    tags: ["LOST", "CLAIM"],
  },
  {
    id: "4",
    title: "Notebook",
    desc: "A5-style notebook, color blue with elastic band.",
    location: "Room 204",
    date: "2026-01-26",
    time: "12:00 PM",
    tags: ["FOUND", "CLAIM"],
  },
  {
    id: "5",
    title: "Tumbler",
    desc: "Stainless steel tumbler, color pink.",
    location: "MAPEH Building",
    date: "2026-02-11",
    time: "5:00 PM",
    image: "/tumbler.png",
    tags: ["LOST", "REPORTED"],
  },
  {
    id: "6",
    title: "Wallet",
    desc: "Leather wallet, color brown.",
    location: "JHS Canteen",
    date: "2026-02-10",
    image: "/wallet.png",
    time: "12:12 PM",
    tags: ["FOUND", "REPORTED"],
  },
  {
    id: "7",
    title: "Cellphone",
    desc: "Blue smartphone, cherry and ribbon case.",
    location: "JHS Canteen",
    date: "2026-02-10",
    time: "12:12 PM",
    image: "/cellphone.png",
    tags: ["FOUND", "REPORTED"],
  },
  {
    id: "8",
    title: "Watch",
    desc: "Gold watch.",
    location: "JHS Canteen",
    date: "2026-02-10",
    time: "12:12 PM",
    image: "/watch.png",
    tags: ["FOUND", "REPORTED"],
  },
];
